-- Up

ALTER TABLE nouns ADD COLUMN author_id TEXT NULL REFERENCES users(id);
ALTER TABLE nouns ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE inclusive ADD COLUMN author_id TEXT NULL REFERENCES users(id);
ALTER TABLE inclusive ADD COLUMN categories TEXT NULL;
ALTER TABLE inclusive ADD COLUMN links TEXT NULL;
ALTER TABLE inclusive ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;

-- Down


