-- Up

ALTER TABLE profiles ADD COLUMN teamName TEXT NULL DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN footerName TEXT NULL DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN footerAreas TEXT NULL DEFAULT NULL;

-- Down
