-- Up

ALTER TABLE census ADD COLUMN ip TEXT NULL DEFAULT NULL;
ALTER TABLE census ADD COLUMN userAgent TEXT NULL DEFAULT NULL;
ALTER TABLE census ADD COLUMN acceptLanguage TEXT NULL DEFAULT NULL;
ALTER TABLE census ADD COLUMN suspicious INTEGER NOT NULL DEFAULT 0;

-- Down
