-- Up

INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3AXDX68MGPNT299YHZ49RAZ', 'cyganić', 'oszukiwać', 'słowo to wywodzi się z negatywnych stereotypów na temat osób romskich', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MS5NQCM06F53JNQ5V7NMV7', 'męstwo', 'odwaga|bohaterstwo|nieustraszoność', 'patriarchalne myślenie łączy pozytywne cechy takie jak odwaga z męstwem, co widać w języku. Stąd warto używać terminu niezwiązanego z płcią. Czasem, dla podkreślenia odwagi kobiet, używa się terminu żeństwo.', 'pl', 1, null, null, 'feminizm', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MSW9YBJE20XKJVSJSC147X', 'pizda|ciota|cipa', 'tchórz, tchórzyni|ciamajda|trzęsidupa|cykor, cykorka', 'kobiece narządy płciowe i ogólnie kobiecość to nie symbol słabości', 'pl', 1, null, null, 'feminizm', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MT3S9HH410H0K1DT990EDZ', 'Bangladesz|Sajgon|Meksyk', 'bałagan|barłóg|bajzel', 'określanie bałaganu nazwami miast i państw jest rasistowskie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MT9NP378JFW9990GDA1076', 'bezdomka', 'sklep Biedronka', 'kryzys bezdomności nie jest niczym zabawnym ani przyjemnym', 'pl', 1, null, null, 'ubóstwo', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MTACD5PZ4NMTHP39RNPZF9', 'Chinol', 'Chińczyk', 'jest to rasistowskie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MTGJYHAFT6TZN9TK5WWVNK', 'ciemno jak w dupie u Murzyna', 'ciemno jak w dupie|ciemno jak w dupie u Hadesa', 'jest to rasistowskie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MTJ2F0GWB521SB0CRGNEY5', 'cnotka niewydymka', 'osoba, która nie chce uprawiać seksu', 'każda osoba ma prawo prowadzić takie życie seksualne jakie chce i nikomu nic do tego', 'pl', 1, null, null, '', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MTMVMQPK9A04RJRG4PEW1J', 'cwel', 'chuj|zjeb|frajek', 'wyzwisko pochodzi z gwary więziennej i oznacza mężczyznę uległego w czasie stosunku z innym mężczyzną, co wiąże się często z gwałtem; często oznacza też homoseksualnego mężczyznę. Jest homofobiczne.
Dlaczego tłumaczymy wyzwiska na bardziej neutralne wyzwiska? Ponieważ w języku potrzebujemy przekleństw do ekspresji.', 'pl', 1, null, null, 'nieheteronormatywność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MTP35GGNC19BV3WWJZJ14E', 'dać dupy', 'zjebać|zepsuć|zawieść', 'bycie bierną stroną podczas stosunku to nie żadna słabość', 'pl', 1, null, null, 'nieheteronormatywność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MVTPRFM20PEAEAEKKR5CVG', 'Kitajce', 'Azjaci', 'określenie rasistowskie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MW2KM37SFDY64JDC1GEB6K', 'robić za Murzyna|Murzyn', 'robić za frajer|frajer', 'w znaczeniu robienia za darmo lub po niskiej cenie określenie stosowane wobec osób czarnoskórych jest rasistowskie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MW98K2FKDGSEQQHR1WPYFN', 'PiSlam ', 'PiSokracja', 'dyskryminaja osób wyznających islam, stereotypizacja tej religii jako autorytarnej', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MWCM8XS3E8TV4WN49XY9YB', 'męska decyzja', 'zdecydowana, odważna decyzja', 'łączenie odwagi i zdecydowania z mężczyznami jest seksistowskie. ', 'pl', 1, null, null, 'feminizm', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MWK84JR231H1NWE79CCG3S', 'dokonać aborcji|usunąć ciążę|zatrzymać dziecko|dziecko nienarodzone|stan błogosławiony|aborcja eugeniczna|kompromis aborcyjny|pro-life', 'mieć/zrobić aborcję|przerwać ciążę|kontynuować ciążę|embrion/płód/zarodek|ciąża|aborcja patoembrionalna|dotychczasowy zakaz aborcji z wyjątk|anti-choice', 'stygmatyzujące lub antynaukowe słownictwo', 'pl', 1, null, null, 'feminizm', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MWTYYNPVK6BVFVZZ8MSAK7', 'rodzaj nijaki', 'rodzaj neutralny', 'słowo nijaki, choć jest dosłownym tłumaczeniem łacińskiego neuter i greckiego οὐδέτερος (udeteros), to nabrało w języku polskim negatywnego znaczenia - jako bezbarwny, bezpłciowy, lichy. Skoro jest to rodzaj gramatyczny używany przez różne osoby, zaproponowano słowo neutralny - analogicznie do ang. neutral grammatical gender, chociaż dosłownym angielskim tłumaczeniem łac. neuter jest neither.', 'pl', 1, null, null, 'transpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MWYAN5QK1C8SKG4R7GE80T', 'preferowane imię|preferowane zaimki', 'używane imię|używane zaimki', 'termin preferowane sugeruje, że jest to coś, co osoba woli, ale rozmówca/czyni nie musi tego wybrać - używane jest terminem lepszym', 'pl', 1, null, null, 'transpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MX1W2N9R3KBZBVSZWTR27F', 'urodził_ się jako kobieta/mężczyzna', 'przypisano je_ męską/żeńską płeć|przy urodzeniu', 'osoby transpłciowe zawsze były swojej płci - po prostu przypisano im inną płeć przy urodzeniu', 'pl', 1, null, null, 'transpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MXHY0PP62Y2JTD0KCE85Z0', 'żydzić|nie bądź Żyd', 'skąpić|nie bądź Harpagon', 'antysemickie określenie utworzone na podstawie stereotypów o osobach narodowości Żydowskiej', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MXJQZFAK62PEJWQ6CEKM7J', 'sierota', 'niezdara', 'strata rodziców jest bolesna', 'pl', 1, null, null, '', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3MXPBF4TN12HH1E8NGRKZ3E', 'Pekin', 'blok o bardzo wielu mieszkaniach', 'rasistowskie określenie wywodzące się z dużej liczby ludności stolicy Chin', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3PZK1FSH51ZPQ0F6VD6FH0P', 'lekkie obyczaje|rozwiązłość', 'posiadanie wielu partnerów seksualny', 'duża ilość seksu i partnerów jest w porządku i nie powinna być stygmatyzowana, mała zresztą też', 'pl', 1, null, null, '', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3PZRJV302FKKQX9V25P0H3R', 'żeńskie chromosomy|męskie chromosomy', 'chromosomy XX|chromosomy XY|chromosomy XXY/XYY/XXX...', 'nie tylko kobiety mają chromosomy XX, nie tylko mężczyźni mają chromosomy XY. Istnieją również inne wariacje chromosomów', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '["https://pl.wikipedia.org/wiki/System_determinacji_p%C5%82ci_XY"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3SPRZ61HB076D2TEDA49ECJ', 'płeć przeciwna', 'inna płeć', 'płeć to wielowymiarowe spektrum, trudno więc mówić tu o przeciwnej płci', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3SPSMKT9G68W8ZHSPMGRX2J', 'płeć piękna', 'kobiety', 'wszystkie płci są piękne', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3SPT5FBBKWR70RE8P3GC4AA', 'Ciapak|Ciapaty', 'Hindus', 'jest to rasistowskie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3SPTSRS5HZG0NBPJ8Q8J1JD', 'murzynek', 'ciasto kakaowe', 'rasistowska nazwa ciasta', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3SPWZPR5YQPVB4PKZVS3145', 'sto lat za Murzynami', 'sto lat za dinozaurami|sto lat za Flinstonami', 'rasistowskie określenie', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F3SPYVN52QJ60QTS61MX0JBF', 'stulejarz|stulejara', 'ofiara losu', 'ableistyczne określenie wobec chorych na stulejkę', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F4EBDE7R0H0K4B7CRYNECPFQ', 'Indianie', 'rdzenni mieszkańcy Ameryki|rdzenni Amerykanie|konkr. plemiona, np. Inuici, Metysi|tubylczy Amerykanie', 'Indianie to kolonialna nazwa wymyślona przez Krzysztofa Kolumba. Rdzenna ludność amerykańska zwykle preferuje inne nazwy.', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F4EBFTM5KHXT0A144DCMTB79', 'genitalia męskie|genitalia żeńskie', 'penis, jądra|pochwa, jajniki', 'kobiety mogą mieć penisa, mężczyźni mogą mieć pochwę', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5E84JR9SVFP0JV585BG5PPH', 'płeć biologiczna', 'płeć metrykalna|płeć przypisana przy urodzeniu|kariotyp', 'płeć biologiczna jest szerokim pojęciem (płeć chromosomalna, płeć hormonalna, płeć narządów wewnętrznych, płeć mózgu itd.) - jeśli masz na myśli płeć w dokumentach lub przypisaną przy urodzeniu w przypadku osób transpłciowych, rozróżnij to', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5MM8Z4X89ES5XYDG6XDGPXH', '„Panie i Panowie”', '„Szanowni Państwo”', 'nie wszyscy ludzie to Panie lub Panowie', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5MN6R4GFVTMGBE5BX1F4YSV', 'Cyganie|Cygan(in)|Cyganka, Romka', 'Romowie|Rom|Romni lm. Romnie', 'słowo Cygan nabrało pejoratywnego znaczenia w języku polskim ze względu na negatywne stereotypy. Chociaż wiele osób romskich neutralnie używa określeń Cygan i Cyganka wobec siebie, w dyskursie publicznym lepiej użyć słów Rom i Romni, oznaczających człowieka i kobietę w języku romskim.', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZFB3Q7937Z0NKB2J06QHBC', 'kocia wiara', 'Chrześcijański Zbór Świadków Jehowy', 'określenie to jest deprymujące wobec tej religii', 'pl', 1, null, null, '', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZFJ6BB5F12NDBSF57VNM96', 'lumpstwo|żulstwo|menelstwo|lujstwo', 'bezdomność', 'kryzys bezdomności jest problemem złożonym i osoby w nim zasługują na szacunek', 'pl', 1, null, null, 'ubóstwo', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZFQ8QJPP851BGFJHMSR17M', 'normalna budowa ciała', 'typowo budowa ciała', 'osoby są zbudowane w bardzo różny sposób, niektóre inaczej niż typowi chłopcy czy dziewczynki', 'pl', 1, null, null, 'interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZFS4788ZJ2F686Y5FXQT8T', 'opalić się na Murzyna', 'bardzo się opalić', 'rasizm wobec osób czarnoskórych', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZGB771A0H396EJBMBBMNFT', 'zespół Downa|mongoloizm|muminek', 'trisomia (chromosomu) 21', 'osoby preferują określenie "trisomia". Down nabrało negatywnych konotacji jako wyzwisko w znaczeniu "głupek". Trisomia 21 chromosomu była nazywana mongolizmem ze względu na podobieństwo osób z trisomią do osób z Azji. Muminek, choć brzmi pozytywnie, jest określeniem upupiającym.', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZGR20A2P6C08BNHQ30MJ2F', 'traktować jak psa|zabić jak psa', 'traktować jak śmiecia|zabić jak śmiecia|traktować/zabić okrutnie', 'przemoc wobec zwierząt jest zła, a takie związki frazeologiczne zachowują status quo i usprawiedliwiają przemoc wobec psów', 'pl', 1, null, null, '', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZH39XJG6STVNAQFKSBED6K', 'inwalidztwo|kalectwo|wada|defekt|upośledzenie', 'niepełnosprawność', 'te określenia traktują niepełnosprawność jako coś złego, a takie osoby jako "niepełnie" i nieważne', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZH7CHS0F8J05PXV7KPSH6J', 'Żółci', 'Azjaci (wschodni)', 'Azjaci wschodni nie mają żółtej skóry, tylko białą', 'pl', 1, null, null, 'rasa i narodowość', '["https://www.scmp.com/week-asia/opinion/article/2184754/chinese-were-white-until-white-men-called-them-yellow"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZKSRNDV4RRHY5S72Z6R6QK', 'autystyczność', 'introwertyczność, wycowanie|zainteresowanie, zafiksowanie', 'nie każda osoba o cechach autystycznych  jest na spektrum autyzmu, nie każda osoba autystyczna jest wycofana, nieśmiała itd.', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZKV99N7BJ5FCBYDSP3J3DB', 'choroba psychiczna|wariactwo', 'głupota', 'głupota nie musi wynikać z choroby psychicznej, a mówienie tak stygmatyzuje osoby chore psychiczne', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZKVMEBDPEQQ65T5BEE0Z8T', 'kobieta|osoba z macicą', 'osoba mogąca zajść w ciążę|osoby zagrożone rakiem piersi', 'zamiast używać nieprecyzyjnych terminów, najlepiej od razu wskazać o co dokładnie chodzi. Nie wszystkie osoby z macicą mogą (czy chcą) zajść w ciążę i na odwrót.', 'pl', 1, null, null, 'interpłciowość,transpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZKWC11V89X60HSPM0FX7BX', 'hormony żeńskie|hormony męskie', 'estrogen|testosteron i androgeny', 'każda osoba niezależnie od płci ma estrogen, testosteron i androgeny w różnych ilościach', 'pl', 1, null, null, 'transpłciowość,interpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZKXN13Y808SRZXWHK4X4W7', 'coś jest z osobą nie tak', 'coś jest z osobą inaczej', 'bycie osobą nienormatywną pod względem orientacji, płci, sprawności itd. nie jest niczym złym', 'pl', 1, null, null, 'nieheteronormatywność,transpłciowość,interpłciowość,niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZM0CNJA0MC3ESM9JD6C10D', 'czuć się kobietą/mężczyzną/niebinarn', 'być kobietą/mężczyzną/niebinarn_', 'osoby są płcią, którą się "czują"', 'pl', 1, null, null, 'transpłciowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZM58JVRNXKK1B5W0KEYCXC', 'gonada obojnacza', 'gonada o utkaniu mieszanym', '"obojnactwo" to niewłaściwy termin', 'pl', 1, null, null, 'interpłciowość', '["https://test.pronouns.page/slowniki/inkluzywny#obojnactwo"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZM72PM0P6VM8Q5NCS6VMM9', 'głuchoniemamota|ślepogłuchoniemota', 'głuchota|ślepogłuchota', 'społeczności Głuchych i Głuchoślepych nie są "nieme" - mają własny język, w przypadku polskiej społeczności Głuchych jest to Polski Język Migowy, a Głuchoniewidomych - Polski Alfabet Larpa', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZM7YA2AJMGF58MY5FA92D5', 'down|debil|kretyn|idiota|imbecyl', 'głupek', 'to medyczne określenia na osoby z różnego rodzaju niepełnosprawnością intelektualną. Chociaż w przypadku niektórych z nich te nazwy medycznie funkcjonują już rzadko, warto o tym pamiętać.', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZM8ZRK2NRDJ4QJ99YQS78W', 'hermafrodytyzm|obojnactwo', 'interpłciowość|międzypłciowość', 'osoby interpłciowe to osoby o niedymorficznej płciowo anatomii (na poziomie chromosomów płci i/lub budowy ciała). Określenie "hermafrodyta" sugeruje, że osoba posiada "dwa zestawy genitaliów" (coś takiego się nie zdarza), jest nieprecyzyjne (istnieje wiele różnorodnych typów interpłciowości; medycyna odchodzi od stosowanych wcześniej określeń "żeński/męski pseudohermafrodytyzm" i "prawdziwy hermafrodytyzm") i może być stygmatyzujące (zob. \[1]), podobnie "obojnak" (o obojnactwie można mówić w przypadku gatunków, których osobniki faktycznie posiadają jednocześnie męskie i żeńskie narządy rozrodcze, np. niektóre gatunki ślimaków, zob. \[2]). Z kolei czasem spotykany (także w tekstach naukowych) termin "interseksualność" budzi (mylne w tym przypadku) skojarzenia seksualnością (por. homoseksualność, biseksualność etc.), stąd określenie "interpłciowość" jest bardziej właściwe (zob. \[3]).Część osób interpłciowych stosuje też określenie "zróżnicowany rozwój płciowy", "zróżnicowane cechy płciowe", ale nie "zaburzenia rozwoju płciowego". zob. \[4]. Interpłciowość to nie zaburzenie, tylko element ludzkiej różnorodności - nasze ciała są różne: mamy różne twarze, różne dłonie, różne włosy... nasze cechy płciowe także są różnorodne).', 'pl', 1, null, null, 'interpłciowość', '["https://pubmed.ncbi.nlm.nih.gov/16200837/","https://pl.wikipedia.org/wiki/Hermafrodytyzm","http://www.poradnikjezykowy.uw.edu.pl/wydania/poradnik_jezykowy.769.2019.10.07-M.Adamczyk.pdf","https://pubmed.ncbi.nlm.nih.gov/28545802/"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZM9JHNRZM61F8X8RD1A98E', 'homoseksualizm, biseksualizm, …|aseksualista, heteroseksualista, …', 'homoseksualność, biseksualność, …|gejowość, lesbijskość, ...|aseksualni, heteroseksualni, ...|asowie, heterycy, ...', 'słowo <em>homoseksualizm</em> powstało w XIX wieku jako termin medyczny. -izmy to choroby (<em>artretyzm, reumatyzm, alkoholizm, hirsutyzm, gigantyzm</em>), postawy (<em>pacyfizm, weganizm</em>) lub ideologie/filozofie (<em>katolicyzm, feminizm, kubizm, modernizm</em>). Orientacja seksualna nie jest żadną z tych rzeczy, jest po prostu cechą, którą posiadamy. Seksualność (a nie <em>seksaulizm</em>) odbiegająca od allocisheteronormatywności nie jest jednak zaburzeniem i nie powinna być nazywana w sposób sugerujący terminologię kliniczną i mający negatywne zabarwienie.

Podobnie, <em>-ista/-istka/-iszczę</em>, to osoba prezentująca jakąś postawę (<em>pacyfistka</em>) lub wyznająca daną ideologię (<em>marksista</em>), stąd lepiej powiedzieć <em>osoba biseksualna</em>, <em>osoba aseksualna</em>, itd.', 'pl', 1, null, null, 'nieheteronormatywność', '["https://depotuw.ceon.pl/bitstream/handle/item/204/Doktorat-J.Rodzoch-Malek.pdf?page=91"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMD9PVAKP4K6S0ZQBWNN7R', 'wieś|wiocha', 'wstyd, obciach|prostactwo', 'klasizm - osoby mieszkające na wsi i z niej pochodzące nie są gorzej wychowane, mniej wyedukowane czy obeznane. ', 'pl', 1, null, null, 'ubóstwo', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMFPBQ8ZZBG8CA9KT99MT5', 'transseskualism|transseksualność', 'transpłciowość', 'transseksualizm (czasem także "transseksualność") to pojęcie medyczne, z czasów gdy transpłciowość traktowano jako zaburzenie psychiczne. Obecnie, światowa organizacja zdrowia odeszła od takiej klasyfikacji transpłciowości, przyznając, że była ona błędna i stygmatyzująca (zob. \[1]). Ponadto, cząstka "-seks-" sugeruje związek z seksualność (por. aseksualność, heteroseksualność), a transpłciowość nie jest orientacją seksualną. Czasem można spotkać się z rozróżnieniem na osoby transseksualne (binarne/i trans kobiety i trans mężczyźni przechodzące_y "pełną tranzycję") i osoby transpłciowe (osoby niebinarne i/lub te, które nie przechodzą tranzycji) (takie rozróżnienie - niestety - znajdziemy np. w broszurce "Język niedyskryminujący" wydanej przez UW, zob. \[2]. Jest ono jednak błędne; bycie osobą trans to po prostu posiadanie tożsamości płciowej innej niż płeć przypisana przy urodzeniu, bez względu na to czy owa tożsamość jest (nie)binarna i czy - oraz w jaki sposób - osoba decyduje się na tranzycję. Jednocześnie, warto zaznaczyć, że część osób trans (zwłaszcza średniego i starszego pokolenia) może stosować w odniesieniu do samych siebie określenia "osoba transseksualna".', 'pl', 1, null, null, 'transpłciowość', '["https://www.euro.who.int/en/health-topics/health-determinants/gender/gender-definitions/whoeurope-brief-transgender-health-in-the-context-of-icd-11","https://www.uw.edu.pl/wp-content/uploads/2020/01/jezyk-niedyskryminujacy.pdf"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMKMK98Z67KYS5VS8Y5QWG', 'na Litwie|na Ukrainie|na Białorusi', 'w Litwie|w Ukrainie|w Białorusi', 'przyimek „<em>na</em>” z tymi państwami pozostał w języku z czasów, kiedy należały one do Rzeczypospolitej. Teraz, kiedy są niepodległe, wyraża to umniejszający i feudalny stosunek wobec nich.', 'pl', 1, null, null, 'rasa i narodowość', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMWJ3VGQZ05ZFCBW0KQ956', 'obie płcie', 'wszystkie płcie|różne płcie', 'czy to pod względem chromosomalnym, genetycznym, fenotypowym czy społecznym; czy to w rozumieniu “płci biologicznej” (sex) czy “płci kulturalnej” (gender) – istnieją więcej niż dwie opcje.', 'pl', 1, null, null, 'interpłciowość,transpłciowość', '["https://twitter.com/RebeccaRHelm/status/1207834357639139328","http://avant.edu.pl/wp-content/uploads/R_Zieminska_Teoria_feministyczna_a_niebinarne_pojecie_plci.pdf"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMXMP9QHS8EXNPXMZ6SR6X', 'Murzyni|Negroidzi/Kongoidzi', 'Czarni/Czarnoskórzy|Afrykanie', 'określenia te mają negatywne skojarzenia. Pochodzą z pseudonaukowej teorii ras, obalonej przez współczesne badania genetyczne', 'pl', 1, null, null, 'rasa,rasa i narodowość', '["http://kosmos.icm.edu.pl/PDF/2009/273.pdf"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMYV7BKYAPZNFQ9483G90F', 'zespół Aspergera', 'autystyczność', 'autyzm to spektrum. Hans Asperger był nazistą, który określał czy dane dzieci "nadają się" do życia a które zasługują na śmierć', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZMZYX4VD5GJB3T3Y02SM3F', 'Osoba z [czymś]|np. Osoba z autyzmem', 'Osoba [jakaś]|np. Osoba autystyczna', 'używanie konstrukcji "z czymś" wymazuje tożsamość tej osoby, danej cecha np. autystyczności. Cechy te nie są wcale obraźliwe, więc nie należy ich tak traktować, są to ważne aspekty czyjejś osobowości.', 'pl', 1, null, null, 'niepełnosprawność', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZN0WKRTDARJE5HHWCPA35Z', 'rodzicielstwo', 'opieka', 'nie wszystkimi dziećmi opiekują się ich rodzice', 'pl', 1, null, null, '', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZN19355697ZWP2Y7N7718T', 'patronat', 'genetriat|matronat|opieka', 'słowo patron pochodzi od łacińskiej nazwy ojca. Organizacje feministyczne często używają, dla walki z męską dominacją jezykową, słowa matronat, pochodzącego od matki. Neutralnym płciowo określeniem byłby genetriat, pochodzący od łacińskich słów genitor/genetrix, oznaczających rodziciela/rodzicielkę', 'pl', 1, null, null, 'feminizm', '[]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZN4TGNPBJKHH2TSRJK0NT4', 'karłowatość', 'niskorośłość', 'słowo posiada negatywne konotacje.', 'pl', 1, null, null, 'niepełnosprawność', '["https://www.youtube.com/watch?v=LiVRl-WKzR8&t=114s&ab_channel=Kasiadzia%C5%82a%21"]', 0);
INSERT INTO inclusive (id, insteadOf, say, because, locale, approved, base_id, author_id, categories, links, deleted) VALUES ('01F5ZNV76V1SA8WZ2TH0GQE396', 'zmiana płci', 'korekta płci|tranzycja', 'płci się nie "zmienia", jedynie koryguje się ciało do oczekiwanego wyglądu. Nie tylko osoby trans korygują swoją płeć, powiększanie piersi czy wydłużanie prącia to zabiegi korekty płci popularne wśród osób cispłciowych', 'pl', 1, null, null, 'transpłciowość', '[]', 0);

-- Down

DELETE FROM "inclusive";
